stages:
  - dist
  - build

variables:
  SURICATA_REPO: "https://github.com/OISF/suricata.git"

# Fedora 31 build. Also create a tar.gz distribution for use by the
# other builds.
fedora-31:
  image: fedora:31
  stage: dist
  before_script:
    - |
      dnf -y install \
        autoconf \
        automake \
        cargo \
        ccache \
        diffutils \
        file-devel \
        gcc \
        gcc-c++ \
        git \
        jansson-devel \
        jq \
        libtool \
        libyaml-devel \
        libnfnetlink-devel \
        libnetfilter_queue-devel \
        libnet-devel \
        libcap-ng-devel \
        libevent-devel \
        libmaxminddb-devel \
        libpcap-devel \
        libtool \
        lua-devel \
        lz4-devel \
        make \
        nspr-devel \
        nss-devel \
        nss-softokn-devel \
        pcre-devel \
        pkgconfig \
        python3-yaml \
        which \
        zlib-devel      
    - git clone "${SURICATA_REPO}"
    - (cd suricata && git clone https://github.com/OISF/libhtp.git)
    - |
      (cd suricata/suricata-update && curl -L \
          https://github.com/OISF/suricata-update/archive/master.tar.gz | \
          tar zxvf - --strip-components=1)
    - cd suricata
  script:
    - ./autogen.sh
    - ./configure
    - make
    - make install
    - make install-conf
    - make install-rules
    - make dist
    - mv suricata-*.tar.gz ..
  artifacts:
    paths:
      - suricata-5.0.0-dev.tar.gz

centos-7:
  image: centos:7
  stage: build
  needs: ["fedora-31"]
  before_script:
    - |
      yum -y install \
        autoconf \
        automake \
        diffutils \
        file-devel \
        gcc \
        gcc-c++ \
        git \
        jansson-devel \
        jq \
        lua-devel \
        libtool \
        libyaml-devel \
        libnfnetlink-devel \
        libnetfilter_queue-devel \
        libnet-devel \
        libcap-ng-devel \
        libevent-devel \
        libmaxminddb-devel \
        libpcap-devel \
        libtool \
        lz4-devel \
        make \
        nss-devel \
        pcre-devel \
        pkgconfig \
        python3-yaml \
        which \
        zlib-devel
    - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y
    - source $HOME/.cargo/env
  script:
    - |
        mkdir suricata
        cd suricata
        tar zxvf ../suricata-*.tar.gz --strip-components=1
        ./configure
        make
        make install
        make install-conf

centos:6:
  image: centos:6
  stage: build
  needs: ["fedora-31"]
  before_script:
    - yum -y install epel-release
    - |
      yum -y install \
        file-devel \
        gcc \
        gcc-c++ \
        jansson-devel \
        jq \
        make \
        libtool \
        libyaml-devel \
        libpcap-devel \
        nss-devel \
        pcre-devel \
        python34-yaml \
        which \
        zlib-devel
    - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y
    - source $HOME/.cargo/env
  script:
    - mkdir suricata
    - cd suricata
    - tar zxvf ../suricata-*.tar.gz --strip-components=1
    - ./configure
    - make
    - make install
    - make install-conf
    - make install-rules
  after_script:
    - test -e /usr/local/share/suricata/classification.config
    - test -e /usr/local/share/suricata/reference.config

debian-9:
  image: debian:9
  stage: build
  needs: ["fedora-31"]
  before_script:
    - apt update
    - |
      apt -y install \
        build-essential \
        jq \
        libpcre3 \
        libpcre3-dbg \
        libpcre3-dev \
        libpcap-dev   \
        libnet1-dev \
        libyaml-0-2 \
        libyaml-dev \
        libcap-ng-dev \
        libcap-ng0 \
        libmagic-dev \
        libjansson-dev \
        libnss3-dev \
        libgeoip-dev \
        liblua5.1-dev \
        libhiredis-dev \
        libevent-dev \
        libtool \
        m4 \
        make \
        python-yaml \
        pkg-config \
        zlib1g \
        zlib1g-dev
    - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y
    - source $HOME/.cargo/env
    - mkdir suricata
    - cd suricata
    - tar xf ../suricata-*.tar.gz --strip-components=1
  script:
    - ./configure
    - make
    - make install
    - make install-conf
    - make install-rules
